### ISSUE TITLE
EmailParser.py

### ISSUE THREAD

**Issue by lokdev** [JakeCooper/OnePlusTwoBot#39]
am getting this error while running emailparser.py

Traceback (most recent call last):
  File "D:\EmailParser.py", line 52, in <module>
    rv, mailboxes = M.list()
  File "C:\Python34\lib\imaplib.py", line 525, in list
    typ, dat = self._simple_command(name, directory, pattern)
  File "C:\Python34\lib\imaplib.py", line 1133, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "C:\Python34\lib\imaplib.py", line 881, in _command
    ', '.join(Commands[name])))
imaplib.error: command LIST illegal in state NONAUTH, only allowed in states AUTH, SELECTED

**Comment by yuya-iwabuchi** [comment]
Allow Less secure apps access by going [here](https://www.google.com/settings/u/1/security/lesssecureapps).
I would recommend you to create alternative account for this usage, as security will be concerned.
