### ISSUE TITLE
EmailParser issue

### ISSUE THREAD

**Issue by manreet** [JakeCooper/OnePlusTwoBot#45]
2-veri is off

Traceback (most recent call last):
  File "C:\Users\Manreet\Desktop\OnePlusTwoBot-master\EmailParser.py", line 53, in <module>
    rv, mailboxes = M.list()
  File "C:\Python34\lib\imaplib.py", line 525, in list
    typ, dat = self._simple_command(name, directory, pattern)
  File "C:\Python34\lib\imaplib.py", line 1133, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "C:\Python34\lib\imaplib.py", line 881, in _command
    ', '.join(Commands[name])))
imaplib.error: command LIST illegal in state NONAUTH, only allowed in states AUTH, SELECTED

**Comment by JakeCooper** [comment]
You need to learn how to search for issues before you just make new ones. This issue has already been solved.
