### ISSUE TITLE
New idea !

### ISSUE THREAD

**Issue by oxicuze** [JakeCooper/OnePlusTwoBot#50]
hi ! why don't we make any brute-force invitation ? a lot of invites card are unused ^^

**Comment by oxicuze** [comment]
I'm not a Genius in Javascript, but there is the clear code of validating system : http://codepen.io/anon/pen/QbRjmy

**Comment by oxicuze** [comment]
fail, there is the invite.js clear with renamed variables :

http://pastebin.com/8Ta4siZQ

**Comment by ikuni123** [comment]
I just found this on a forum, I'm not into python but it looks like it works:
http://pastebin.com/sSW0f3Ge

**Comment by qwerty123443** [comment]
@ikuni123 downloaded, testing now. will update and create a pull request if it works.
@oxicuze that's likeley not the correct code. if they have any brain power (which they have) they'll do it server-side only

**Comment by ikuni123** [comment]
@qwerty123443 it works, but it probably takes weeks until you get an invite this way

**Comment by ghost** [comment]
For the Bruteforce script, it says:
"Steps to use: 1. replace email1 with your email and password with your password. this is used to claim the invite. 2. replace email2 with another (or the same) email. this is the email where the invites will be sent. 3. run invite_bruteforce.py"

Do you have to input the password for your gmail or the OnePlus password that you signed up your email with?

**Comment by qwerty123443** [comment]
You have to input your gmail password
Op 31 aug. 2015 10:01 PM schreef "Has" notifications@github.com:

**Comment by ghost** [comment]
It does not work, It goes up to 6-20K and stops and gives an error.

**Comment by ikuni123** [comment]
@ahmadhas03 Error Code? I never went so high

**Comment by ghost** [comment]
LOL! So did u find the code?

**Comment by ahmadhas03** [comment]
If you could pls send me the invite code?
haseebahmad02@gmail.com

Thanks

**Comment by ikuni123** [comment]
I just wanted to know what error it gives you

**Comment by ghost** [comment]
ok, i am running it again and if I get that error again, I'll send the screenshot.

**Comment by ikuni123** [comment]
Perfect

**Comment by ghost** [comment]
I would like to know how you ran the code and what files (scripts) you need.
I only ran this file: <a href="http://pastebin.com/sSW0f3Ge" target="_blank">invite_bruteforce.py</a> in terminal "**python invite_bruteforce.py**"

**Comment by ikuni123** [comment]
That is all you need to do, just don't forget to change the emails like mentioned in the Readme (https://github.com/qwerty123443/OnePlusTwoBot/blob/master/README.md).
You can also change the time.sleep(2) at the end of the code to 1 or comment it out.

**Comment by ghost** [comment]
I used the same email in the `<email1>` and `<email2>` tags and in the `<password>` tag, I used the password for my gmail account.

**Comment by ikuni123** [comment]
That should work

**Comment by ghost** [comment]
Just want to know, upto what number did yours go?

**Comment by ikuni123** [comment]
5k without any problems

**Comment by ghost** [comment]
ok thanks mine is >650 no problems yet

**Comment by ghost** [comment]
I'm over 5K, but still no invite lol

**Comment by ikuni123** [comment]
As I said it could take weeks to find a invite, as there are only a few out there

The only other way I see is to write a bot that searches the forum for invite codes or posts in every new thread

**Comment by ghost** [comment]
Thanks @ikuni123
I'll reply when/If I get the error. Hopefully I don't get an error lol

**Comment by ghost** [comment]
Im stuck at attempt 9870

**Comment by ghost** [comment]
Ran it again and here is the error I got:

```
Traceback (most recent call last):
  File "invite_bruteforce.py", line 48, in <module>
    res1 = urllib2.urlopen(req1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:590)>
Username$ Url1: https://invites.oneplus.net/claim/GL0O-ZRD3-BTUP-ULJF
-bash: Url1:: command not found
```

I was at Attempt 7496.

**Comment by ikuni123** [comment]
You can try this: http://stackoverflow.com/questions/11772847/error-urlopen-error-errno-8-ssl-c504-eof-occurred-in-violation-of-protoco
But on your specific Error I can only find this: http://stackoverflow.com/questions/31869238/urlerror-occurred-when-i-use-mechanize-to-scrap-the-website
